version: 2.1

description: |
  Remove composer dev dependencies:
  https://github.com/t3n/circleci-orbs

executors:
  ci-image:
    description: The docker container to use when running composer commands
    docker:
      - image: t3nde/ci-build:7.3
jobs:
  remove-dev:
    description: Remove composer dev dependencies
    executor: ci-image
    parameters:
      workspace-root:
        type: string
        default: ~/workspace
      working-directory:
        type: string
        default: app
    steps:
      - attach_workspace:
          at: << parameters.workspace-root >>
      - run: |
          cd << parameters.workspace-root >> 
          cd << parameters.working-directory >> 
          composer --ignore-platform-reqs install --no-dev
      - persist_to_workspace:
          root: << parameters.workspace-root >>
          paths:
            - << parameters.working-directory >>
